// Code from github.com/mububoki/jpeg2000 v1.0.0 (MIT); see internal/jpeg2000/LICENSE and PROVENANCE.md.

package codestream

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// parseQCDSegment runs processQCD over a marker segment (the bytes starting at
// the Lqcd field, i.e. just after the 0xFF5C marker) and returns the parsed QCD.
func parseQCDSegment(t *testing.T, seg []byte) QCD {
	t.Helper()
	d := &Decoder{r: bytes.NewReader(seg), section: sectionMainHeader}
	if err := d.processQCD(); err != nil {
		t.Fatalf("processQCD: %v", err)
	}
	return d.header.qcd
}

// Real QCD segment from an OpenJPEG lossy (9x7, scalar expounded) 64x64 file,
// generated by `opj_compress -r 20 -I`. opj_dump reports:
//
//	qntsty=2 numgbits=2
//	stepsizes (m,e)= (1824,14) (1776,14) (1776,14) (1728,14) (1792,13) (1792,13)
//	  (1760,13) (1872,12) (1872,12) (1896,12) (5,10) (5,10) (71,10) (2003,10)
//	  (2003,10) (1890,10)
func TestProcessQCD_ScalarExpounded(t *testing.T) {
	seg, err := hex.DecodeString("002342772076f076f076c06f006f006ee067506750676850055005504757d357d35762")
	if err != nil {
		t.Fatal(err)
	}
	qcd := parseQCDSegment(t, seg)

	if qcd.Style != qStyleExpounded {
		t.Errorf("Style = %d, want %d (expounded)", qcd.Style, qStyleExpounded)
	}
	if qcd.Reversible {
		t.Errorf("Reversible = true, want false for scalar quantization")
	}
	if qcd.GuardBits != 2 {
		t.Errorf("GuardBits = %d, want 2", qcd.GuardBits)
	}

	// (Expn, Mant) pairs as reported by opj_dump (m,e).
	want := []QCDStepSize{
		{14, 1824}, {14, 1776}, {14, 1776}, {14, 1728},
		{13, 1792}, {13, 1792}, {13, 1760},
		{12, 1872}, {12, 1872}, {12, 1896},
		{10, 5}, {10, 5}, {10, 71}, {10, 2003}, {10, 2003}, {10, 1890},
	}
	if len(qcd.StepSizes) != len(want) {
		t.Fatalf("got %d step sizes, want %d", len(qcd.StepSizes), len(want))
	}
	for i, w := range want {
		if qcd.StepSizes[i] != w {
			t.Errorf("step[%d] = {Expn:%d Mant:%d}, want {Expn:%d Mant:%d}",
				i, qcd.StepSizes[i].Expn, qcd.StepSizes[i].Mant, w.Expn, w.Mant)
		}
	}
}

// TestProcessQCD_NoQuantization covers the reversible (lossless) style: one byte
// per subband, exponent in bits 7-3, mantissa implicitly zero.
func TestProcessQCD_NoQuantization(t *testing.T) {
	// Lqcd=7, Sqcd=0x40 (style 0, guard bits 2), then 4 subband bytes.
	// exponents 8,9,9,10 -> bytes (e<<3): 0x40, 0x48, 0x48, 0x50.
	seg := []byte{0x00, 0x07, 0x40, 8 << 3, 9 << 3, 9 << 3, 10 << 3}
	qcd := parseQCDSegment(t, seg)

	if qcd.Style != qStyleNone || !qcd.Reversible {
		t.Errorf("Style=%d Reversible=%v, want style 0 / reversible", qcd.Style, qcd.Reversible)
	}
	if qcd.GuardBits != 2 {
		t.Errorf("GuardBits = %d, want 2", qcd.GuardBits)
	}
	wantExpn := []int{8, 9, 9, 10}
	if len(qcd.StepSizes) != len(wantExpn) {
		t.Fatalf("got %d step sizes, want %d", len(qcd.StepSizes), len(wantExpn))
	}
	for i, e := range wantExpn {
		if qcd.StepSizes[i].Expn != e || qcd.StepSizes[i].Mant != 0 {
			t.Errorf("step[%d] = {Expn:%d Mant:%d}, want {Expn:%d Mant:0}",
				i, qcd.StepSizes[i].Expn, qcd.StepSizes[i].Mant, e)
		}
	}
}

// TestProcessQCD_ScalarDerived covers the derived style: a single 2-byte entry.
func TestProcessQCD_ScalarDerived(t *testing.T) {
	// Lqcd=5, Sqcd=0x21 (style 1 derived, guard bits 1), one entry 0x7720.
	seg := []byte{0x00, 0x05, 0x21, 0x77, 0x20}
	qcd := parseQCDSegment(t, seg)

	if qcd.Style != qStyleDerived || qcd.Reversible {
		t.Errorf("Style=%d Reversible=%v, want derived / not reversible", qcd.Style, qcd.Reversible)
	}
	if qcd.GuardBits != 1 {
		t.Errorf("GuardBits = %d, want 1", qcd.GuardBits)
	}
	if len(qcd.StepSizes) != 1 {
		t.Fatalf("got %d step sizes, want 1", len(qcd.StepSizes))
	}
	if qcd.StepSizes[0] != (QCDStepSize{Expn: 14, Mant: 1824}) {
		t.Errorf("step[0] = %+v, want {Expn:14 Mant:1824}", qcd.StepSizes[0])
	}
}
