// Copyright (c) 2026 by Richard A. Wilkes. All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, version 2.0. If a copy of the MPL was not distributed with
// this file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// This Source Code Form is "Incompatible With Secondary Licenses", as
// defined by the Mozilla Public License, version 2.0.

package jbig2

import (
	"bytes"
	"fmt"
	"testing"
)

// This file carries no build tag on purpose: every benchmark here runs the same code in the default build and under
// GOEXPERIMENT=simd, so one benchmark body measures both arms and benchstat can difference them. It also holds the
// pieces the tagged equivalence tests share with the benchmarks — the PRNG and the image builders — because a tagged
// file cannot be seen from an untagged one, and the fill test, which has to run in both builds because fillBytes is
// scalar code that compiles into both.

// composeOpNames pairs each composition operator with a name for benchmark and failure output. Replace is included
// because the unaligned kernel handles it too: SubImage composes with it, at whatever bit offset the caller asked
// for.
var composeOpNames = []struct {
	name string
	op   ComposeOp
}{
	{name: "Or", op: ComposeOr},
	{name: "And", op: ComposeAnd},
	{name: "Xor", op: ComposeXor},
	{name: "Xnor", op: ComposeXnor},
	{name: "Replace", op: ComposeReplace},
}

// prng is a splitmix64 generator. The tests need reproducible bytes, and math/rand is off the table in this repo
// (gosec G404), so this is the whole generator: one add, three xor-shifts, two multiplies.
type prng uint64

// next returns the next value in the sequence.
func (p *prng) next() uint64 {
	*p += 0x9e3779b97f4a7c15
	z := uint64(*p)
	z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9
	z = (z ^ (z >> 27)) * 0x94d049bb133111eb
	return z ^ (z >> 31)
}

// fill fills b with generated bytes.
func (p *prng) fill(b []byte) {
	for i := range b {
		b[i] = byte(p.next() >> 24)
	}
}

// randomImage returns a w by h image whose bits are generated, including any padding bits past the right edge, which
// is what a real decoded bitmap looks like only in that composition must leave them alone the same way.
func randomImage(p *prng, w, h int32) *Image {
	img := NewImage(w, h)
	p.fill(img.data)
	return img
}

// TestFillBytesMatchesBytewise proves the doubling copy fills exactly what the byte-at-a-time loops it replaced
// filled, on both sides of its length gate and at every length through several doublings.
//
// This test is untagged because fillBytes is: it is scalar code that the default build compiles and runs, and the
// three call sites it serves — Image.Fill, Image.Expand, and the MMR black-run fill — are on the default decode path.
func TestFillBytesMatchesBytewise(t *testing.T) {
	original := fillBytesMin
	t.Cleanup(func() { fillBytesMin = original })
	for _, gate := range []int{1, 2, 32, 1 << 30} {
		fillBytesMin = gate
		for n := range 200 {
			want := make([]byte, n+8)
			got := make([]byte, n+8)
			for i := range want {
				want[i] = 0x5A
				got[i] = 0x5A
			}
			for i := 4; i < n+4; i++ {
				want[i] = 0xFF
			}
			fillBytes(got[4:n+4], 0xFF)
			if !bytes.Equal(got, want) {
				t.Fatalf("fillBytes(len=%d) with gate %d: got %x, want %x", n, gate, got, want)
			}
		}
	}
}

// BenchmarkComposeBytesSIMD measures the byte-aligned composition path at the row lengths JBIG2 actually produces:
// 8 and 16 bytes are symbol rows, 320 is a full-width row of a 2550 pixel page, and 1024 is a wide region.
func BenchmarkComposeBytesSIMD(b *testing.B) {
	var rng prng = 1
	for _, size := range []int{8, 16, 64, 320, 1024} {
		src := make([]byte, size)
		dst := make([]byte, size)
		rng.fill(src)
		rng.fill(dst)
		for _, entry := range composeOpNames {
			if entry.op == ComposeReplace {
				continue // Replace is a copy in both arms; there is nothing to compare.
			}
			b.Run(fmt.Sprintf("%s/n%d", entry.name, size), func(b *testing.B) {
				for b.Loop() {
					composeBytesFn(dst, src, entry.op)
				}
			})
		}
	}
}

// BenchmarkComposeShiftedSIMD measures the unaligned placement path at every bit offset. Widths 16 and 64 are symbol
// rows, the size text regions place thousands of times per page, and both sit below the length gate, so they measure
// what the dispatch point costs a row the kernel never takes; 96 is the first width above it; 2550 is a full page
// width, which is what a region composed onto a page at an odd offset moves.
//
// Each iteration composes the whole 32-row image, so the fixed cost of ComposeTo's clipping math is amortized the way
// a real region composition amortizes it, while the per-row costs — the head byte, the call into the dispatch
// variable, the trailing bytes — are counted 32 times, as they are on a real placement.
func BenchmarkComposeShiftedSIMD(b *testing.B) {
	const rows = 32
	var rng prng = 2
	for _, width := range []int32{16, 64, 96, 2550} {
		src := randomImage(&rng, width, rows)
		dst := randomImage(&rng, width+16, rows)
		for shift := int32(1); shift <= 7; shift++ {
			for _, entry := range composeOpNames {
				if entry.op != ComposeOr && entry.op != ComposeXnor {
					continue // Or is what text regions use; Xnor is the costliest arm. The rest track them.
				}
				b.Run(fmt.Sprintf("%s/w%d/shift%d", entry.name, width, shift), func(b *testing.B) {
					for b.Loop() {
						src.ComposeTo(dst, shift, 0, entry.op)
					}
				})
			}
		}
	}
}

// BenchmarkFillSIMD measures Image.Fill on a full page. The fill has no vector kernel — the doubling copy in
// fillBytes measured faster than one — so both arms of this benchmark run the same code, and a difference between
// them means something other than the fill moved.
func BenchmarkFillSIMD(b *testing.B) {
	img := NewImage(2550, 3300)
	for b.Loop() {
		img.Fill(true)
	}
}

// BenchmarkFillBytewiseSIMD is the baseline BenchmarkFillSIMD replaced: the byte-at-a-time loop that stood at
// Image.Fill, Image.Expand, and the MMR black-run fill before fillBytes. It is here so the drop rule has a number to
// compare the doubling copy against.
func BenchmarkFillBytewiseSIMD(b *testing.B) {
	img := NewImage(2550, 3300)
	for b.Loop() {
		for idx := range img.data {
			img.data[idx] = 0xFF
		}
	}
}
