// Code from github.com/mububoki/jpeg2000 v1.0.0 (MIT); see internal/jpeg2000/LICENSE and PROVENANCE.md.

package e2e_test

import (
	"testing"
)

// Multi-tile images generated by OpenJPEG 2.4.0 (lossless) with `-t W,H`.
// These exercise SOT-driven per-tile decoding and tile reassembly into the full
// image plane, including boundary tiles when the image size is not a multiple of
// the tile size.

func TestDecode_GrayTile32_T16(t *testing.T) {
	// 32x32 grayscale, 16x16 tiles (2x2 = 4 tiles), 2 DWT levels.
	decodeAndCheckPGM(t, "../testdata/graytile32_t16.j2k", "../testdata/graytile32.pgm")
}

func TestDecode_GrayTile48x40_T32(t *testing.T) {
	// 48x40 grayscale, 32x32 tiles: a 2x2 grid with cropped right/bottom boundary
	// tiles (16-wide and 8-tall remainders).
	decodeAndCheckPGM(t, "../testdata/graytile48x40_t32.j2k", "../testdata/graytile48x40.pgm")
}

func TestDecode_RGBTile32_T16(t *testing.T) {
	// 32x32 RGB (RCT), 16x16 tiles (2x2 = 4 tiles), 2 DWT levels.
	decodeAndCheckPPM(t, "../testdata/rgbtile32_t16.j2k", "../testdata/rgb32.ppm")
}
