// Code from github.com/mububoki/jpeg2000 v1.0.0 (MIT); see internal/jpeg2000/LICENSE and PROVENANCE.md.

package e2e_test

import (
	"bufio"
	"bytes"
	"fmt"
	"image"
	"io"
	"os"
	"testing"

	_ "github.com/richardwilkes/pdfview/internal/jpeg2000/j2k"
	_ "github.com/richardwilkes/pdfview/internal/jpeg2000/jp2"
)

// readPGM reads a binary (P5) 8-bit grayscale PGM and returns width, height, pixels.
func readPGM(t *testing.T, path string) (int, int, []uint8) {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()
	r := bufio.NewReader(f)

	var magic string
	if _, err := fmt.Fscan(r, &magic); err != nil {
		t.Fatalf("read magic: %v", err)
	}
	if magic != "P5" {
		t.Fatalf("unsupported PGM magic %q (want P5)", magic)
	}
	var w, h, maxval int
	if _, err := fmt.Fscan(r, &w, &h, &maxval); err != nil {
		t.Fatalf("read header: %v", err)
	}
	if maxval > 255 {
		t.Fatalf("maxval %d > 255 not supported", maxval)
	}
	// Single whitespace byte separates the header from binary data.
	if _, err := r.Discard(1); err != nil {
		t.Fatalf("discard header separator: %v", err)
	}
	pix := make([]uint8, w*h)
	if _, err := io.ReadFull(r, pix); err != nil {
		t.Fatalf("read pixels: %v", err)
	}
	return w, h, pix
}

// decodeAndCheckPGM decodes a J2K/JP2 file and compares against a ground-truth PGM.
func decodeAndCheckPGM(t *testing.T, j2kPath, pgmPath string) {
	t.Helper()
	w, h, expected := readPGM(t, pgmPath)
	decodeAndCheck(t, j2kPath, w, h, expected)
}

// decodeAndCheck decodes a J2K file and compares pixels against expected values.
func decodeAndCheck(t *testing.T, path string, w, h int, expected []uint8) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}

	imgI, _, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("Decode error: %v", err)
	}

	bounds := imgI.Bounds()
	if bounds.Dx() != w || bounds.Dy() != h {
		t.Fatalf("size mismatch: got %dx%d, want %dx%d", bounds.Dx(), bounds.Dy(), w, h)
	}

	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			r, _, _, _ := imgI.At(x, y).RGBA()
			got := uint8(r >> 8)
			want := expected[y*w+x]
			if got != want {
				t.Errorf("pixel(%d,%d): got %d, want %d", x, y, got, want)
			}
		}
	}
}

// All test files are generated by OpenJPEG 2.4.0 with lossless compression.

func TestDecode_Gray4x4_N1(t *testing.T) {
	// 4x4 grayscale, 1 decomposition level (levels=0 in COD since opj uses -n 1)
	expected := make([]uint8, 16)
	for i := range expected {
		expected[i] = uint8(i)
	}
	decodeAndCheck(t, "../testdata/gray4x4_n1.j2k", 4, 4, expected)
}

func TestDecode_Gray8x8_N1(t *testing.T) {
	// 8x8 grayscale, 1 decomposition level
	expected := make([]uint8, 64)
	for i := range expected {
		expected[i] = uint8(i)
	}
	decodeAndCheck(t, "../testdata/gray8x8_n1.j2k", 8, 8, expected)
}

func TestDecode_Gray8x8_N2(t *testing.T) {
	// 8x8 grayscale, 2 decomposition levels
	expected := make([]uint8, 64)
	for i := range expected {
		expected[i] = uint8(i)
	}
	decodeAndCheck(t, "../testdata/gray8x8_n2.j2k", 8, 8, expected)
}

func TestDecode_OnePixel_N1(t *testing.T) {
	// 4x4 grayscale: pixel(0,0)=255, rest=128
	expected := make([]uint8, 16)
	for i := range expected {
		expected[i] = 128
	}
	expected[0] = 255
	decodeAndCheck(t, "../testdata/one_pixel_n1.j2k", 4, 4, expected)
}

func TestDecode_Uniform8x8_N1(t *testing.T) {
	// 8x8 grayscale, all pixels = 128
	expected := make([]uint8, 64)
	for i := range expected {
		expected[i] = 128
	}
	decodeAndCheck(t, "../testdata/uniform8x8_n1.j2k", 8, 8, expected)
}

func TestDecode_JP2_Gray4x4(t *testing.T) {
	// 4x4 grayscale JP2 container, pixels = 0..15
	expected := make([]uint8, 16)
	for i := range expected {
		expected[i] = uint8(i)
	}
	decodeAndCheck(t, "../testdata/gray4x4.jp2", 4, 4, expected)
}

// Larger real images, exercising multi-stripe code-blocks and the HL/LH detail
// subbands. These previously decoded to garbage due to two Tier-1 context bugs
// (sign context same/opposite-sign swap, and the HL/LH zero-coding h/v swap);
// both are fixed.

func TestDecode_Gray64x64_N2(t *testing.T) {
	// 64x64 grayscale with gradient+checker pattern, 2 decomposition levels (opj -n 3).
	decodeAndCheckPGM(t, "../testdata/gray64x64_n2.j2k", "../testdata/gray64x64.pgm")
}

func TestDecode_Gray64x64_N5(t *testing.T) {
	// Same image, 5 decomposition levels (opj -n 6) to exercise deeper DWT.
	decodeAndCheckPGM(t, "../testdata/gray64x64_n5.j2k", "../testdata/gray64x64.pgm")
}
