// Code from github.com/mububoki/jpeg2000 v1.0.0 (MIT); see internal/jpeg2000/LICENSE and PROVENANCE.md.

package e2e_test

import (
	"bufio"
	"bytes"
	"fmt"
	"image"
	"io"
	"os"
	"testing"

	_ "github.com/richardwilkes/pdfview/internal/jpeg2000/j2k"
	_ "github.com/richardwilkes/pdfview/internal/jpeg2000/jp2"
)

// readPPM reads a binary (P6) 8-bit RGB PPM and returns width, height, and
// interleaved RGB pixels (3 bytes per pixel).
func readPPM(t *testing.T, path string) (int, int, []uint8) {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()
	r := bufio.NewReader(f)

	var magic string
	if _, err := fmt.Fscan(r, &magic); err != nil {
		t.Fatalf("read magic: %v", err)
	}
	if magic != "P6" {
		t.Fatalf("unsupported PPM magic %q (want P6)", magic)
	}
	var w, h, maxval int
	if _, err := fmt.Fscan(r, &w, &h, &maxval); err != nil {
		t.Fatalf("read header: %v", err)
	}
	if maxval > 255 {
		t.Fatalf("maxval %d > 255 not supported", maxval)
	}
	if _, err := r.Discard(1); err != nil {
		t.Fatalf("discard header separator: %v", err)
	}
	pix := make([]uint8, w*h*3)
	if _, err := io.ReadFull(r, pix); err != nil {
		t.Fatalf("read pixels: %v", err)
	}
	return w, h, pix
}

// decodeAndCheckPPM decodes a J2K/JP2 RGB file and compares against a P6 PPM.
// This exercises the reversible color transform (RCT) and the packet-header
// bit-stuffing path (a 0xFF byte inside a packet header desyncs the bit reader
// unless the post-0xFF stuff bit is honored).
func decodeAndCheckPPM(t *testing.T, srcPath, ppmPath string) {
	t.Helper()
	w, h, expected := readPPM(t, ppmPath)
	data, err := os.ReadFile(srcPath)
	if err != nil {
		t.Fatalf("read %s: %v", srcPath, err)
	}
	imgI, _, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("Decode error: %v", err)
	}
	bounds := imgI.Bounds()
	if bounds.Dx() != w || bounds.Dy() != h {
		t.Fatalf("size mismatch: got %dx%d, want %dx%d", bounds.Dx(), bounds.Dy(), w, h)
	}
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			r, g, b, _ := imgI.At(x, y).RGBA()
			gr, gg, gb := uint8(r>>8), uint8(g>>8), uint8(b>>8)
			i := (y*w + x) * 3
			if gr != expected[i] || gg != expected[i+1] || gb != expected[i+2] {
				t.Errorf("pixel(%d,%d): got (%d,%d,%d), want (%d,%d,%d)",
					x, y, gr, gg, gb, expected[i], expected[i+1], expected[i+2])
			}
		}
	}
}

// RGB images generated by OpenJPEG 2.4.0 (lossless, MCT/RCT on). The 32x32 image
// has a high-entropy blue channel, so component packet headers contain 0xFF
// bytes — regression coverage for packet-header bit-stuffing and inverse RCT.

func TestDecode_RGB16_N1(t *testing.T) {
	// 16x16 RGB, single decomposition level (opj -n 1).
	decodeAndCheckPPM(t, "../testdata/rgb16_n1.j2k", "../testdata/rgb16.ppm")
}

func TestDecode_RGB32_N2(t *testing.T) {
	// 32x32 RGB, 2 decomposition levels (opj -n 2).
	decodeAndCheckPPM(t, "../testdata/rgb32_n2.j2k", "../testdata/rgb32.ppm")
}

func TestDecode_JP2_RGB32_N2(t *testing.T) {
	// Same 32x32 RGB image in a JP2 container.
	decodeAndCheckPPM(t, "../testdata/rgb32_n2.jp2", "../testdata/rgb32.ppm")
}
